{% set name = "DAWG-Python" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a5e3286e6261cca02f205cfd5516a7ab10190fa30c51c28d345808f595e3421

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  
requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - dawg_python
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/kmike/DAWG-Python/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pure-python reader for DAWGs (DAFSAs) created by dawgdic C++ library or DAWG Python extension.
  description: |
    Pure-python reader for DAWGs (DAFSAs) created by dawgdic C++ library or DAWG Python extension.
  doc_url: https://pypi.org/project/DAWG-Python/
  dev_url: https://github.com/kmike/DAWG-Python/

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - benhuff
    - oblute
